name: learning_action
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
        - name: checkout code
          uses: actions/checkout@v3
        - name: setup python
          uses: actions/setup-python@v4
          with:
            python-version: 3.11
        - name: install dependencies
          run: |
            cd src && pip install -r requirements.txt
            cd ..
        - name: run tests
          run: |
            PYTHONPATH=src pytest tests/ --cov=src --cov-report=xml
        - name: Upload Job Artifacts
          uses: actions/upload-artifact@v7
          with:
            name: test-results
            path: coverage.xml

  build_job:
    needs: test_job
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: build docker image
        run: |
          docker compose build flaskapp
      - name: save docker image
        run: |
          docker save -o flaskapp.tar flaskapp:latest
      - name: Upload Job Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: docker-image
          path: flaskapp.tar
            